### ISSUE TITLE
aioes broken with ES 5.x

### ISSUE THREAD

**Issue by merrellb** [aio-libs/aioes#112]
It appears the fix is trivial and a few pull requests have already been submitted.  I prefer the approach in:
https://github.com/aio-libs/aioes/pull/48

**Comment by zpoint** [comment]
Unable to add http headers with aioes
with elasticsearch==5.1.0
I can pass header parameters as **kwargs in __init__

**Comment by pfreixes** [comment]
@popravich is there any plan to release the current master as a 0.6.2 aioes version or something like that  ? ES 5.X was released half year ago, will be nice to have a "fixed" release  :)

**Comment by popravich** [comment]
Yeah, will do a release shortly)

**Comment by popravich** [comment]
Done! https://pypi.python.org/pypi/aioes/0.7.0

**Comment by pfreixes** [comment]
this week? I would like to avoid do a reference in our requirements to a specific commit to master branch 😉
