### ISSUE TITLE
implement pluggable serializer

### ISSUE THREAD

**Issue by omerbenamram** [aio-libs/aioes#146]
Hello,

In the current state - the transport handles the dumping and loading of documents internally - using `json.dumps`.

Id like to use [ujson](https://github.com/esnme/ultrajson) for example, but without editing the sources of aioes.

the official ES client implements a Serializer interface - which conviniently supports changing the serializer backend (for example - mentioned here - [https://github.com/elastic/elasticsearch-py/issues/365](https://github.com/elastic/elasticsearch-py/issues/365)).

Would you consider implementing such an interface?

**Comment by hellysmile** [comment]
Try to take a look on https://github.com/wikibusiness/aioelasticsearch , there existing interface
