### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by roll** [aio-libs/aioes#27]
It looks like there is no chance to use HTTP Basic Auth for now?

**Comment by asvetlov** [comment]
No, but basic auth support can be added easy.
Would you like making a Pull Request?

**Comment by roll** [comment]
Thanks. I'll make a shot. Monkeypathed Connection.perform_request works. It looks like I just have to provide http_auth string/tuple parameter thru Elasticearch and Transport classes.

**Comment by asvetlov** [comment]
Yes, `http_auth` looks good. It should be `aiohttp.BasicAuth` parameter: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/helpers.py#L14

**Comment by mpaolini** [comment]
implemented in #40

**Comment by mpaolini** [comment]
I think we can close this one as done. See #40

**Comment by mpaolini** [comment]
ping we can close this

**Comment by asvetlov** [comment]
Thanks
