### ISSUE TITLE
aioes 0.2 release

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioes#30]
I'd like to make new release, version 0.2 should support Python 3.5

Is anything left to be done before the release publishing?

**Comment by schettino72** [comment]
I think it would be a good idea to specify exactly which version of elasticsearch each version supports (was tested).

I tried to run the `cmp.py` script but it didnt work at all. Give me a few more days and will look into it... :)

**Comment by asvetlov** [comment]
Sounds good. Let me know when you will be ready.

**Comment by asvetlov** [comment]
I'd like to drop Python 3.3 support since upcoming aiohttp 0.18 will do it.
Objections?

**Comment by schettino72** [comment]
No objections to drop python 3.3.
And from my side you can go on and make a new release, I do not plan to work on anything else.
 Cheers

**Comment by asvetlov** [comment]
Done
