### ISSUE TITLE
What versions of Elasticsearch does this support?

### ISSUE THREAD

**Issue by owaaa** [aio-libs/aioes#45]
I cant find it anywhere in the docs or the source code. Does this support the 1.X and 2.X series of ES?

**Comment by asvetlov** [comment]
It's tested on 1.X
Sorry, I don't use ES right now and don't follow its REST API changes.

**Comment by owaaa** [comment]
Is this library maintained then? The updates seem fairly recent

**Comment by asvetlov** [comment]
It's maintained but not actively developed.
But if you want to make a PR for explicitly supporting ES 2.X -- you are welcome.

**Comment by excentro123** [comment]
Hello.
I'm using aioes with ES 2.2.0. Works fine.

2016-09-26 22:20 GMT+03:00 Andrew Svetlov <notifications@github.com>:

**Comment by szborows** [comment]
we're using it with ES 2.7 with no problems.
in a hour or two we will check 5.x

**Comment by szborows** [comment]
unfortunately aioes doesn't seem to work with ES 5.x
even adding an index doesn't work with following error
`aioes.exception.RequestError: TransportError(400, 'No handler found for uri [//dupa] and method [PUT]')`

**Comment by popravich** [comment]
aioes has Elasticsearch 5.x support since v0.7.

**Comment by popravich** [comment]
see [.travis.yml](https://github.com/aio-libs/aioes/blob/master/.travis.yml#L44) for target Elasticsearch server versions
