### ISSUE TITLE
aiohttp 1.2+ ClientSession issues

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aioes#83]
If Elasticsearch created outside coroutine it produces aiohttp warning

`ERROR [asyncio] Creating a client session outside of coroutine`

due

https://github.com/KeepSafe/aiohttp/blob/c4539a7f3851483c985fa885f7e4a151e3bc3d43/aiohttp/client.py#L57

**Comment by asvetlov** [comment]
See aio-libs/aiobotocore#85
